#!/bin/bash
# Hide the details of the one-jar SBT build plug-ins.  Unfortunately, sbt's wrapper script does not
# seem to be amenable to passing arguments transparently.  IOW, neither `sbt run $@` or `sbt "run $@"` work

sbt one-jar

java -jar target/scala*/*one-jar.jar $@
